version: "3"

services:
    nginx:
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - ./core.oc.kzn.local.conf:/etc/nginx/conf.d/core.oc.kzn.local.conf
        - ./logs/nginx:/var/log/nginx
        - ./www:/www
      links:
        - php-fpm

    php-fpm:
      image: php:5.6-fpm
      build: ./php-fpm
      volumes:
        - ./www:/www



